FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /App
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM build AS migration
ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet tool install --global dotnet-ef --version 6.0.0
ENTRYPOINT ["dotnet", "ef", "database", "update"]