// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RineaR.Spring.Common;

#nullable disable

namespace RineaR.Spring.Migrations
{
    [DbContext(typeof(SpringDbContext))]
    [Migration("20230924170251_init4")]
    partial class init4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RineaR.Spring.Common.ActionBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MarvelousScore")
                        .HasColumnType("int");

                    b.Property<int>("PainfulScore")
                        .HasColumnType("int");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ActionBase");

                    b.HasDiscriminator<string>("ActionType").HasValue("ActionBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RineaR.Spring.Common.SchedulerJobState", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastRunTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("SchedulerJobState");
                });

            modelBuilder.Entity("RineaR.Spring.Common.User", b =>
                {
                    b.Property<ulong>("DiscordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("GitHubID")
                        .HasColumnType("longtext");

                    b.HasKey("DiscordID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("RineaR.Spring.Common.BedIn", b =>
                {
                    b.HasBaseType("RineaR.Spring.Common.ActionBase");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime(6)");

                    b.HasDiscriminator().HasValue("BedIn");
                });

            modelBuilder.Entity("RineaR.Spring.Common.Comfort", b =>
                {
                    b.HasBaseType("RineaR.Spring.Common.ActionBase");

                    b.Property<ulong>("DiscordMessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("DiscordReactionId")
                        .HasColumnType("int");

                    b.Property<int>("TargetPainfulScore")
                        .HasColumnType("int");

                    b.Property<ulong>("TargetUserId")
                        .HasColumnType("bigint unsigned");

                    b.HasIndex("TargetUserId");

                    b.HasDiscriminator().HasValue("Comfort");
                });

            modelBuilder.Entity("RineaR.Spring.Common.DailyContribution", b =>
                {
                    b.HasBaseType("RineaR.Spring.Common.ActionBase");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("DailyContribution");
                });

            modelBuilder.Entity("RineaR.Spring.Common.Login", b =>
                {
                    b.HasBaseType("RineaR.Spring.Common.ActionBase");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime(6)");

                    b.ToTable("ActionBase", t =>
                        {
                            t.Property("ApplicationDate")
                                .HasColumnName("Login_ApplicationDate");
                        });

                    b.HasDiscriminator().HasValue("Login");
                });

            modelBuilder.Entity("RineaR.Spring.Common.Praise", b =>
                {
                    b.HasBaseType("RineaR.Spring.Common.ActionBase");

                    b.Property<ulong>("DiscordMessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("DiscordReactionId")
                        .HasColumnType("int");

                    b.Property<int>("TargetMarvelousScore")
                        .HasColumnType("int");

                    b.Property<ulong>("TargetUserId")
                        .HasColumnType("bigint unsigned");

                    b.HasIndex("TargetUserId");

                    b.ToTable("ActionBase", t =>
                        {
                            t.Property("DiscordMessageId")
                                .HasColumnName("Praise_DiscordMessageId");

                            t.Property("DiscordReactionId")
                                .HasColumnName("Praise_DiscordReactionId");

                            t.Property("TargetUserId")
                                .HasColumnName("Praise_TargetUserId");
                        });

                    b.HasDiscriminator().HasValue("Praise");
                });

            modelBuilder.Entity("RineaR.Spring.Common.WakeUp", b =>
                {
                    b.HasBaseType("RineaR.Spring.Common.ActionBase");

                    b.Property<int>("BedInId")
                        .HasColumnType("int");

                    b.Property<int>("ResultType")
                        .HasColumnType("int");

                    b.HasIndex("BedInId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("WakeUp");
                });

            modelBuilder.Entity("RineaR.Spring.Common.ActionBase", b =>
                {
                    b.HasOne("RineaR.Spring.Common.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RineaR.Spring.Common.Comfort", b =>
                {
                    b.HasOne("RineaR.Spring.Common.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("RineaR.Spring.Common.Praise", b =>
                {
                    b.HasOne("RineaR.Spring.Common.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("RineaR.Spring.Common.WakeUp", b =>
                {
                    b.HasOne("RineaR.Spring.Common.BedIn", "BedIn")
                        .WithOne("WakeUp")
                        .HasForeignKey("RineaR.Spring.Common.WakeUp", "BedInId");

                    b.Navigation("BedIn");
                });

            modelBuilder.Entity("RineaR.Spring.Common.BedIn", b =>
                {
                    b.Navigation("WakeUp");
                });
#pragma warning restore 612, 618
        }
    }
}
